on:
  push:
    branches:
      - main

name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploying
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Getting the latest code
        uses: actions/checkout@v3

      - name: 📂 Sync
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.gospelcommunityfellowship.com
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: /public_html

      - name: Install Composer Dependencies
        run: composer update

      - name: Install NPM Packages
        run: npm install
